apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: 20221174/ci-cd:1.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
  labels:
    app: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-container
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "cancanii!"
        - name: MYSQL_DATABASE
          value: "canIuseit_db"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: db-app
  clusterIP: None
